version: '3'
services:
  db:
    image: mysql:latest
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"

  # app:
  #   build:
  #     context: .
  #     dockerfile: ./docker/app/Dockerfile
  #   command: bundle exec rails s -p 4000 -b '0.0.0.0'
  #   volumes:
  #     - .:/var/www/app
  #   depends_on:
  #     - db
  #
  # web:
  #   build:
  #     context: .
  #     dockerfile: ./docker/web/Dockerfile
  #   depends_on:
  #     - app
  #   ports:
  #     - "80:80"

volumes:
  data: {}
